#此為mongo in docker的設定檔 (含gui)
#啟用： docker-compose up -d
#先uv sync後到指定虛擬環境(.venv\Scripts\Activate5)
#在Studio 3T中輸入 mongodb://root:secretpassword@localhost:27018/
#關閉：docker-compose down
#退出虛擬環境：deactivate

version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    restart: always
    environment:
      # 設定 root 帳號密碼
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    ports:
      # 將主機的 27017 埠對應到容器的 27017 埠
      - "27018:27017"
    volumes:
      # 將資料庫檔案掛載到本地的 mongo_data 資料夾，這樣容器關閉資料才不會不見
      - ./mongo_data:/data/db

  # (可選) 視覺化介面，讓組員可以在瀏覽器看資料
  mongo-express:
    image: mongo-express
    container_name: my_mongo_express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secretpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:secretpassword@mongodb:27017/
    depends_on:
      - mongodb